# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    # env:
    #   working-directory: /home/chanfi/Apps/

    # defaults:
    #   run:
    #     working-directory: ${{ env.working-directory }}


    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #  defaults:
  #    run:
  #      working-directory: /home/chanfi/Apps/

    steps:
    - uses: actions/checkout@v3
        clean: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # GITHUB_WORKSPACE: /home/chanfi/Apps/git

    - run: ln -s /home/chanfi/Runners/checkConsulado/_work/checkConsulado/sesionWSP /home/chanfi/Runners/checkConsulado/_work/checkConsulado/checkConsulado/.wwebjs_auth

    - run: npm i
    
    - run: pm2 reload checkConsulado
      # working-directory: ${{env.working-directory}}
#run: npm run build --if-present
#    - run: echo "pruebita andando ok"
     

# FUENTE: https://stackoverflow.com/questions/72360263/how-to-checkout-a-repository-outside-of-the-workspace-in-github-actions
# steps:
#   - uses: actions/checkout@v3
#   - run: mv /path/to/my/folder /path/to/my/target